apiVersion: v1
kind: ConfigMap
metadata:
  name: git-cm
data:
  source: "https://github.com/dell-alekseipopov/k8s-devops.git"

---

apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: myapp
spec:
  containers:
  - name: nginx
    image: nginx-latest
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: cdn
  initContainers:
  - name: init-step1 # INIT 1 
    image: alpine/git:latest
    command: ['git', 'clone', '$(GIT_PATH)', '/cdn']
    env:
      - name: GIT_PATH
        valueFrom:
          configMapKeyRef:
            name: git-cm
            key: source
    volumeMounts:
    - mountPath: /cdn
      name: cdn
  volumes:
  - name: cdn
    emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  ports:
  - port: 80
    nodePort: 80
    targetPort: http-port
    protocol: TCP
  selector:
    app: myapp
  type: LoadBalancer